// Code generated by Slice Machine. DO NOT EDIT.

import SidesBlock from "./SidesBlock";
import TestBlock from "./TestBlock";

export const components = {
  sides_block: SidesBlock,
  test_block: TestBlock,
};
