// Code generated by Slice Machine. DO NOT EDIT.

import SidesBlock from "./SidesBlock";
import TestBlock from "./TestBlock";
import TestBlock2 from "./TestBlock2";

export const components = {
  sides_block: SidesBlock,
  test_block: TestBlock,
  test_block2: TestBlock2,
};
